apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: {{ .Values.csi.keyvaultName }}
    objects: |
      array:
        - objectName: {{ .Values.csi.secretKeys.username }}
          objectType: secret
        - objectName: {{ .Values.csi.secretKeys.password }}
          objectType: secret
        - objectName: {{ .Values.csi.secretKeys.host }}
          objectType: secret
        - objectName: {{ .Values.csi.secretKeys.db-name }}
          objectType: secret
    tenantId: {{ .Values.csi.tenantId }}
